3370 1
OnlineMediaSolutions/bcwork pull request #208
Opened 2024-11-17 08:11 UTC by sonaisrayel

2024-11-17 08:55 UTC, denis-s-oms requested changes

2024-11-17 08:55 UTC, denis-s-oms commented on utils/constant/global_factor.go
> +type GlobalFactor struct {
No need to create new type of entity we already have - https://github.com/OnlineMediaSolutions/bcwork/blob/main/core/global_factor.go#L50

Moreover this is not constant. It will be better to move this struct in package `dto` and replace it everywhere it is used.

2024-11-17 08:55 UTC, denis-s-oms commented on utils/helpers/publisher.go
> +type Publisher struct {
Same as global factors

2024-11-17 08:55 UTC, denis-s-oms commented on workers/email_reports/real_time_report/data.go
> +type Publisher struct {
Same as global factors. Also looks like duplicate.

2024-11-17 08:55 UTC, denis-s-oms commented on workers/email_reports/real_time_report/email.go
> +	//formatter := &helpers.FormatValues{}
If you commented this line, then there is no need in `/helpers/formatter.go`.

2024-11-17 08:55 UTC, denis-s-oms commented on utils/helpers/publisher.go
> +func FetchPublishers(ctx context.Context) (map[string]string, error) {
I don't think that this should be part of helpers. Looks like it is one of steps of worker. Also httpClient should be creating while initializing worker.

2024-11-17 08:55 UTC, denis-s-oms commented on utils/helpers/fees.go
> +func FetchFees(ctx context.Context) (map[string]float64, map[string]float64, error) {
I don't think that this should be part of helpers. Looks like it is one of steps of worker. Also httpClient should be creating while initializing worker.

2024-11-17 08:55 UTC, denis-s-oms commented on workers/email_reports/real_time_report/data.go
> +func (worker *Worker) FetchFromQuest(ctx context.Context, start time.Time, end time.Time) (map[string]*RealTimeReport, error) {
Name of methods doesn't reflect what it is doing. You are not only receive data from quest, but also from our API (global factor, publisher)

2024-11-17 08:57 UTC, finkiel commented on utils/helpers/fees.go
> +		if item.Key == "consultant_fee" && item.PublisherID != "" {
please set all strings as constant or as Enum (we might have more fees in the future)

2024-11-17 08:57 UTC, finkiel commented on workers/email_reports/real_time_report/worker.go
> +	emailCredsMap, err := config.FetchConfigValues([]string{"real_time_report"})
you are using this string: "real_time_report" in couple of places in your code - you can set it as a const

2024-11-17 08:57 UTC, finkiel commented on workers/email_reports/real_time_report/worker.go
> +	if worker.skipInitRun {
great

2024-11-17 08:57 UTC, finkiel commented on workers/email_reports/real_time_report/worker.go
> +	worker.Start = worker.End.Add(-7 * 24 * time.Hour)
why -7?
if it's because of time difference than we'll have to change it twice a year, maybe there's a better solution?

2024-11-17 08:57 UTC, finkiel commented on workers/email_reports/real_time_report/worker.go
> +		fmt.Println("Error fetching records for real time report:", err)
please print as log and not as fmt.Println - log also supply timestamp so we can do better monitoring if needed in the future
moreover, we should try to keep same convention as much as possible

2024-11-17 08:57 UTC, finkiel commented on utils/helpers/formatter.go
> +type FormatValues struct{}
maybe I'm missing something but didn't see any usage of those functions in the code

2024-11-17 08:57 UTC, finkiel commented on workers/email_reports/real_time_report/worker.go
> +		dateI := helpers.FormatDate(reports[i].Time)
what is dateI and what is DateJ - can you please change the name to something more informative

2024-11-17 09:00 UTC, sonaisrayel commented on workers/email_reports/real_time_report/email.go
> +	//formatter := &helpers.FormatValues{}
I am waiting for Mateo , maybe we need this. If no I will remove

2024-11-17 13:54 UTC, sonaisrayel commented on utils/constant/global_factor.go
> +type GlobalFactor struct {
I created it because using core.GlobalFactor causing circular dependeces alert in code. I will move it to dto as you suggested

2024-11-18 07:07 UTC, denis-s-oms commented on utils/helpers/fees.go
> +		if item.Key == "consultant_fee" && item.PublisherID != "" {
https://github.com/OnlineMediaSolutions/bcwork/blob/main/utils/constant/constants.go#L22

2024-11-18 09:13 UTC, sonaisrayel commented on workers/email_reports/real_time_report/worker.go
> +	worker.Start = worker.End.Add(-7 * 24 * time.Hour)
@finkiel -7 means seven day before today.

2024-11-18 09:26 UTC, sonaisrayel commented on utils/helpers/formatter.go
> +type FormatValues struct{}
I will delete if Mateo says that we dont need format values

2024-12-08 08:45 UTC, denis-s-oms commented on workers/email_reports/real_time_report/email.go
> +	reportType := reflect.TypeOf(EmailReport{})
Didn't get idea of this. You get field names using reflect, but then (on line 73) you write values using exact struct and strict order of fields, so looks like this reflect usage doesn't do anything. If you want to use reflect (to make this function more generic), then you also need to write values using reflection. For now you dynamically could get fields names but not values.

2024-12-08 08:45 UTC, denis-s-oms commented on utils/constant/calculations.go
> +type GPParameters struct {
I didn't find any usage of this struct, do we need it?

2024-12-08 08:45 UTC, denis-s-oms commented on utils/constant/calculations.go
> +type GPResults struct {
Same as GPParameters

2024-12-08 08:45 UTC, denis-s-oms commented on workers/email_reports/real_time_report/data.go
> +	rec.TechFee = helpers.RoundFloat(fees["tech_fee"] * rec.BidRequests / 1000000)
`1000000` looks like "magic number". It's better to create a constant for it

2024-12-08 08:45 UTC, denis-s-oms commented on workers/email_reports/real_time_report/data.go
> +	HttpClient := httpclient.New(true)
You have already created httpClient when worker was initialized. Maybe this function should be as worker's method?

2024-12-08 17:40 UTC, sonaisrayel commented on utils/constant/calculations.go
> +type GPParameters struct {
not in use, deleted

2024-12-08 17:40 UTC, sonaisrayel commented on utils/constant/calculations.go
> +type GPResults struct {
not in use, deleted

2024-12-08 17:43 UTC, sonaisrayel commented on workers/email_reports/real_time_report/data.go
> +	rec.TechFee = helpers.RoundFloat(fees["tech_fee"] * rec.BidRequests / 1000000)
done

2024-12-08 17:46 UTC, sonaisrayel commented on workers/email_reports/real_time_report/data.go
> +	HttpClient := httpclient.New(true)
done

2024-12-08 18:07 UTC, sonaisrayel commented on workers/email_reports/real_time_report/email.go
> +	reportType := reflect.TypeOf(EmailReport{})
I am using reflect to avoid hard coded column names, I need to generate it dynamically

2024-12-09 12:56 UTC, sonaisrayel commented on workers/email_reports/real_time_report/email.go
> +	reportType := reflect.TypeOf(EmailReport{})
done

2024-12-09 14:05 UTC, denis-s-oms approved these changes

2024-12-09 15:15 UTC, merged