Bid cashing
OnlineMediaSolutions/bcwork pull request #220
Opened 2024-11-26 10:12 UTC by sonaisrayel

2024-11-27 10:13 UTC, finkiel commented on core/bid_caching.go
> +		return fmt.Errorf("failed to parse hash value for bidCaching: %w", err)
you're not parsing, you are marshling

2024-11-27 10:13 UTC, finkiel commented on api/rest/bid_caching.go
> +// @Success 200 {object} BidCachingUpdateResponse
this is not the response object that you are returning, but another object ( utils.BaseResponse)

2024-11-27 10:13 UTC, finkiel commented on api/rest/bid_caching_test.go
> +			name: "Sort By Correct Order",
great and important test!

2024-11-27 10:13 UTC, finkiel commented on api/rest/bid_caching_test.go
> +package rest
great tests!

2024-11-27 11:01 UTC, finkiel commented on validations/validation.go
> +	err = Validator.RegisterValidation("refresh_cache", refreshCacheValidation)
you're allowing the refresh value to be 0, pretty sure it should be higher than 0 (minimum 1)

2024-11-27 11:08 UTC, finkiel commented on core/refresh_caching.go
> +	modRefreshCache, err := RefreshCacheQuery(c, updateRequest)
Yesterday we said the the bid_cache value in Metadata will hold all the parameters with all the rules
and refresh_caching not

the key is OK but the value should be only a number (don't need to write the rules as in factor/floor/dpo....

2024-11-27 11:13 UTC, sonaisrayel commented on validations/validation.go
> +	err = Validator.RegisterValidation("refresh_cache", refreshCacheValidation)
Gil says it can be empty , will check once more time with him

2024-11-27 11:15 UTC, sonaisrayel commented on core/refresh_caching.go
> +	modRefreshCache, err := RefreshCacheQuery(c, updateRequest)
sorry, didn't listen about it, will change it now

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/bid_caching_test.go
> +	app := fiber.New()
There is no need to create instance of fiber application. There is one in `api/rest/rest_test.go`. It's better to add route to it.

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/bid_caching_test.go
> +		req := httptest.NewRequest("POST", "/bid_caching", strings.NewReader(test.body))
Your tests are testing only validation, which is better to move to package `validations`. Also it would better to add tests for handler functionality.

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/bid_caching.go
> +	err = o.bidCachingService.UpdateMetaData(c.Context(), *data)
It shouldn't be different method. There is no need to router to know that when bid caching rule creating there is also need to update metadata.

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/bid_caching_test.go
> +			result := core.CreateBidCachingMetadata(tt.modBC, tt.finalRules)
You import function from `core`, so it's better to move test to package `core`

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/bid_caching_test.go
> +func Test_BC_ToModel(t *testing.T) {
Same. It's not test for `rest` package.

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/refresh_cache.go
> +	err = o.refreshCacheService.UpdateMetaData(c.Context(), *data)
Same as for bid caching.

2024-12-01 14:37 UTC, denis-s-oms commented on api/rest/refresh_cache_test.go
> +	app := fiber.New()
Same comments as for bid caching

2024-12-01 14:37 UTC, denis-s-oms commented on cmd/api.go
> +	app.Post("/bid_caching", validations.ValidateBidCaching, omsNP.BidCachingPostHandler)
On last week we discussed with Yiftah, general flow for rules shouldn't allow update (or it should be limited to value. So we need separate methods for create, delete, and partial update.

2024-12-01 14:37 UTC, denis-s-oms commented on core/refresh_cache.go
> +type RefreshCache struct {
This is also `dto`

2024-12-01 14:37 UTC, denis-s-oms commented on core/bid_caching.go
> +type BidCaching struct {
This is also `dto`

2024-12-02 11:51 UTC, sonaisrayel commented on cmd/api.go
> +	app.Post("/bid_caching", validations.ValidateBidCaching, omsNP.BidCachingPostHandler)
will do this during developing delete functionality

2024-12-04 14:55 UTC, finkiel commented on api/rest/bidCaching_test.go
> +func TestValidateBidCachings(t *testing.T) {
great tests
please add a valid test - a one that everythings works

2024-12-04 14:55 UTC, finkiel commented on api/rest/refresh_cache.go
> +		return utils.ErrorResponse(c, fiber.StatusBadRequest, "Failed to update metadata table for refresh cache", err)
error message is incorrect - you're deleting not updating

2024-12-04 14:55 UTC, finkiel commented on api/rest/refresh_cache.go
> +		return utils.ErrorResponse(c, fiber.StatusInternalServerError, "Failed to update Refresh cache table", err)
error message is incorrect - failed to soft delete not update

2024-12-04 14:55 UTC, finkiel commented on api/rest/refresh_cache_test.go
> +func TestValidateRefreshCache(t *testing.T) {
please add test where everything works ok

2024-12-05 09:25 UTC, denis-s-oms requested changes
Most cruical parts are:
1. Deleting `refresh_cache` rule;
2. Format of `refresh_cache` rule. Because now it differ from what we discussed at the beginning and expecting in `bidder-v2`;

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +		wrappedStrings = append(wrappedStrings, fmt.Sprintf(`'%s'`, generateMetadataKey(rc)))
Method `FromModel` fill `res` with value of domain which could be empty string. Will it be processed correct if we have a key like `refresh:cache:20138:*`? Seems that with empty domain it will be like `refresh:cache:20138:` and that key couldn't be found in DB.

Also in function `SendRefreshCacheToRT` you use different approach to generate key.

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache_test.go
> +			expected: "UPDATE refresh_cache SET active = false WHERE rule_id IN ();",
This query will be failed. I'm not sure we should expect this.

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +	old, err := b.prepareHistory(ctx, mod)
Error is ignored

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +	mod, err := models.RefreshCaches(models.RefreshCacheWhere.RuleID.EQ(data.RuleId)).One(ctx, bcdb.DB())
Error is ignored

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +		err = SendRefreshCacheToRT(context.Background(), res)
Same as for bid_cache. Leads to possible inconsistency

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +	old, err := r.prepareHistory(ctx, mod)
Error is ignored. Also we can't have `old` when we haven't created `new` yet.

2024-12-05 09:25 UTC, denis-s-oms commented on migrations/025_refresh_cache.up.sql
> +    domain            varchar(256)                                   not null,
Domain is not mandatory so why it should be `not null`?

2024-12-05 09:25 UTC, denis-s-oms commented on migrations/025_refresh_cache.up.sql
> +    demand_partner_id varchar(64)      default ''::character varying not null,
Is it necessary to have `demand_partner_id` as empty string? Why `not null`?

2024-12-05 09:25 UTC, denis-s-oms commented on migrations/024_bid_caching.up.sql
> +    demand_partner_id varchar(64)      default ''::character varying not null,
Is it necessary to have `demand_partner_id` as empty string? Why `not null`?

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +	mods, _ := models.RefreshCaches(models.RefreshCacheWhere.RuleID.IN(refreshCache)).All(ctx, bcdb.DB())
Error is ignored

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +	err = mod.Upsert(
It's better to use `Update` instead of `Upsert` since methods for creating and updating are separated.

2024-12-05 09:25 UTC, denis-s-oms commented on core/refresh_cache.go
> +		err = SendRefreshCacheToRT(context.Background(), *data)
Same as for bid_cache. Leads to possible inconsistency

2024-12-05 09:33 UTC, sonaisrayel commented on api/rest/bid_caching.go
> +	err = core.UpdateBidCachingMetaData(*data)
@denis-s-oms  I dont want to ignore your comment, I think I changed it

2024-12-07 20:08 UTC, sonaisrayel commented on core/bid_caching.go
> +type BidCaching struct {
@denis-s-oms I am getting this error while trying to move struct to dto package 
`Invalid receiver type '*dto.BidCaching' ('dto.BidCaching' is a non-local type)`
for get rid of this, I need to create local type like this 
`type LocalBidCaching struct {
    *dto.BidCaching
}`

if you have another option , please help me with this.

2024-12-07 20:10 UTC, sonaisrayel commented on api/rest/bidCaching_test.go
> +package rest
done

2024-12-07 20:11 UTC, sonaisrayel commented on validations/bidCachingValidation.go
> +package validations
done

2024-12-07 20:11 UTC, sonaisrayel commented on validations/refreshCacheValidation.go
> +package validations
done

2024-12-07 20:13 UTC, sonaisrayel commented on migrations/025_refresh_cache.up.sql
> +    demand_partner_id varchar(64)      default ''::character varying not null,
I use same migration file as we have in factor

2024-12-07 20:13 UTC, sonaisrayel commented on migrations/024_bid_caching.up.sql
> +    demand_partner_id varchar(64)      default ''::character varying not null,
I use same migration file as we have in factor

2024-12-07 20:24 UTC, sonaisrayel commented on core/refresh_cache.go
> +	err = mod.Upsert(
done

2024-12-07 20:26 UTC, sonaisrayel commented on core/refresh_cache.go
> +		err = SendRefreshCacheToRT(context.Background(), *data)
done

2024-12-08 09:23 UTC, sonaisrayel commented on core/refresh_cache.go
> +	mods, _ := models.RefreshCaches(models.RefreshCacheWhere.RuleID.IN(refreshCache)).All(ctx, bcdb.DB())
done

2024-12-08 09:23 UTC, sonaisrayel commented on core/refresh_cache.go
> +	err = mod.Upsert(
done

2024-12-08 09:24 UTC, sonaisrayel commented on core/refresh_cache.go
> +		err = SendRefreshCacheToRT(context.Background(), *data)
done

2024-12-08 09:25 UTC, sonaisrayel commented on api/rest/refresh_cache.go
> +		return utils.ErrorResponse(c, fiber.StatusBadRequest, "Failed to update metadata table for refresh cache", err)
done

2024-12-08 09:27 UTC, sonaisrayel commented on api/rest/refresh_cache.go
> +		return utils.ErrorResponse(c, fiber.StatusInternalServerError, "Failed to update Refresh cache table", err)
done

2024-12-08 11:02 UTC, sonaisrayel commented on core/bid_caching.go
> +type BidCaching struct {
done

2024-12-08 13:10 UTC, sonaisrayel commented on api/rest/refresh_cache_test.go
> +func TestValidateRefreshCache(t *testing.T) {
done

2024-12-08 13:34 UTC, denis-s-oms commented on core/refresh_cache.go
> +	old, err := r.prepareHistory(ctx, mod)
^^^

2024-12-09 08:21 UTC, denis-s-oms commented on core/bid_caching.go
> +		return err, nil
You return error as value for history, but error itself is returned as nil

2024-12-09 08:24 UTC, denis-s-oms commented on api/rest/refresh_cache_test.go
> +			name: "Some fields empty",
Looks similar as test `All fields populated`. Maybe you wanted domain to be empty?

2024-12-09 08:59 UTC, sonaisrayel commented on migrations/025_refresh_cache.up.sql
> +    domain            varchar(256)                                   not null,
done

2024-12-09 09:05 UTC, sonaisrayel commented on api/rest/refresh_cache_test.go
> +			name: "Some fields empty",
done

2024-12-09 09:10 UTC, sonaisrayel commented on core/bid_caching.go
> +		return err, nil
return oldMod, nil
I changed like this

2024-12-09 09:24 UTC, sonaisrayel commented on api/rest/rest_test.go
> +	appTest.Post("/test/refresh_cache", validations.ValidateRefreshCache, omsNPTest.RefreshCacheSetHandler)
Will write quickly

2024-12-09 11:49 UTC, sonaisrayel commented on api/rest/rest_test.go
> +	appTest.Post("/test/refresh_cache", validations.ValidateRefreshCache, omsNPTest.RefreshCacheSetHandler)
done

2024-12-09 16:59 UTC, finkiel approved these changes

2024-12-10 06:27 UTC, finkiel approved these changes

2024-12-10 09:35 UTC, denis-s-oms approved these changes

2024-12-10 09:36 UTC, merged