Active flag in /floor/get API and /factor/get
OnlineMediaSolutions/bcwork pull request #242
Opened 2024-12-16 04:54 UTC by sonaisrayel

[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3464)

1. Add active status for factor api
2. Add active status for floor api
3. Move structs and model components to dto package

2024-12-16 07:24 UTC, denis-s-oms requested changes

2024-12-16 07:24 UTC, denis-s-oms commented on core/factor_delete.go
> +	Active    filter.StringArrayFilter `json:"active,omitempty"`
Why it should be string array? You have only two possible values here - `true` and `false`. It should be `filter.BoolFilter`.

2024-12-16 07:24 UTC, denis-s-oms commented on api/rest/floor_test.go
> -func TestFloorGetAllHandler(t *testing.T) {
I understand that you moved this test to validation. But it's better not to delete it and write a successful one.

2024-12-16 07:24 UTC, denis-s-oms commented on core/floor.go
> +	Active    filter.StringArrayFilter `json:"active"`
Same as for `Factor`

2024-12-16 09:37 UTC, sonaisrayel commented on core/factor_delete.go
> +	Active    filter.StringArrayFilter `json:"active,omitempty"`
as we discuss in daily we will keep and will change in one ticket all this cases

2024-12-16 09:37 UTC, sonaisrayel commented on core/floor.go
> +	Active    filter.StringArrayFilter `json:"active"`
as we discuss in daily we will keep and will change in one ticket all this cases

2024-12-16 09:53 UTC, finkiel approved these changes

2024-12-16 09:58 UTC, sonaisrayel commented on api/rest/floor_test.go
> -func TestFloorGetAllHandler(t *testing.T) {
@denis-s-oms I wrote this test in rest because I need to use appTest and when I write  test in validation it's making error messages.

2024-12-17 14:13 UTC, sonaisrayel commented on api/rest/floor_test.go
> -func TestFloorGetAllHandler(t *testing.T) {
done

2024-12-18 10:04 UTC, sonaisrayel commented on core/factor_delete.go
> +	Active    filter.StringArrayFilter `json:"active,omitempty"`
will be developed it other ticket.
done

2024-12-18 10:05 UTC, sonaisrayel commented on core/floor.go
> +	Active    filter.StringArrayFilter `json:"active"`
will be developed it other ticket.
done

2024-12-18 11:50 UTC, denis-s-oms approved these changes

2024-12-18 12:11 UTC, merged